---
stages:
  - test

lint:
  tags:
    - kubernetes
  stage: test
  image: golang:1.18.0
  script:
    - go mod tidy
    - make lint

test:
  tags:
    - kubernetes
  stage: test
  image: golang:1.18.0
  script:
    - go test ./...
