// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	ingest "github.com/connylabs/ingest"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CleanUp provides a mock function with given fields: _a0, _a1
func (_m *Client) CleanUp(_a0 context.Context, _a1 ingest.Identifiable) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ingest.Identifiable) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Download provides a mock function with given fields: _a0, _a1
func (_m *Client) Download(_a0 context.Context, _a1 ingest.Identifiable) (ingest.Object, error) {
	ret := _m.Called(_a0, _a1)

	var r0 ingest.Object
	if rf, ok := ret.Get(0).(func(context.Context, ingest.Identifiable) ingest.Object); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ingest.Object)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ingest.Identifiable) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
