// Code generated by mockery v2.10.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Dequeuer is an autogenerated mock type for the Dequeuer type
type Dequeuer struct {
	mock.Mock
}

// Dequeue provides a mock function with given fields: _a0
func (_m *Dequeuer) Dequeue(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Runner provides a mock function with given fields: _a0
func (_m *Dequeuer) Runner(_a0 context.Context) func() error {
	ret := _m.Called(_a0)

	var r0 func() error
	if rf, ok := ret.Get(0).(func(context.Context) func() error); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() error)
		}
	}

	return r0
}
