// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Dequeuer is an autogenerated mock type for the Dequeuer type
type Dequeuer struct {
	mock.Mock
}

// Dequeue provides a mock function with given fields: _a0
func (_m *Dequeuer) Dequeue(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDequeuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewDequeuer creates a new instance of Dequeuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDequeuer(t mockConstructorTestingTNewDequeuer) *Dequeuer {
	mock := &Dequeuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
