// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Enqueuer is an autogenerated mock type for the Enqueuer type
type Enqueuer struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: _a0
func (_m *Enqueuer) Enqueue(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEnqueuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewEnqueuer creates a new instance of Enqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEnqueuer(t mockConstructorTestingTNewEnqueuer) *Enqueuer {
	mock := &Enqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
